### ISSUE TITLE
Figure not found on global installation

### ISSUE THREAD

**Issue by sibebleuze** [driesbenoit/ugent-doc#2]
First of all, what a wonderful idea to make a LaTeX template out of the UGent Word templates. I look forward to using this.
Now I imagine you probably need feedback on how to improve this, so allow me to make the first suggestion.

I tried to do the global installation (on Windows) as described in your readme. To my surprise I actually got it to work. The only thing that appears not to work is when I create a file with the ugent-doc class, it cannot find the pdfs with the logos that are in the figures folder of this repo. I can fix it by adding the absolute path to the folder with ugent-doc.cls to the `\graphicspath`, but I was wondering if there was any possible way to have it auto-detect the figures folder that is next to ugent-doc.cls. If there is, I wouldn't need an absolute path in my .tex file anymore, which would be a good thing in my opinion.

Steps to reproduce:

1. Install ugent-doc in a TDS compliant folder, add that folder to the Miktex root folders and refresh FNBD.
2. Copy the example.tex file from the examples folder to some other location on your computer. Remove the lines with the frog image and the references or make sure they will get resolved (the issue is not about those).
3. Try to compile the document (I use Texstudio). This will fail because ugent-nl.pdf or ugent-en.pdf cannot be found, in addition to the faculty logo.

If you need any more info or log files from me, just let me know.

**Comment by driesbenoit** [comment]
Thank for your interest in the template!
Normally this issue should have been fixed with commit https://github.com/driesbenoit/ugent-doc/commit/d5e869d4701b79302febd211ddc585c5dac102cc ("remove paths to figures in cls file"). In the cls file, there should be no paths to the logos, only the name of the logo files. When the class is installed globally, the TeX engine will do a recursive search in your LaTeX directory to find the logo files.

Can you check if your local version contains these recent changes that were made? If not, please pull the last version and try again. Thx.

Note that I've also updated the readme (see Ad Hoc Installation) where some more information is given about the lack of paths to the logo files in the cls.

**Comment by driesbenoit** [comment]
Also note that I've just removed the dependency of the example on the frog picture. Now a default `example-image` is used.

**Comment by arthur-thuy** [comment]
I just installed the LaTeX template. I can confirm that commit https://github.com/driesbenoit/ugent-doc/commit/d5e869d4701b79302febd211ddc585c5dac102cc solved the issue.  The LaTeX template now works using a global installation on Windows (MikTex).

**Comment by sibebleuze** [comment]
Yes, it works for me too, so I'll close the issue then.
